### ISSUE TITLE
Error during dump: ValueError: math domain error

### ISSUE THREAD

**Issue by joelands** [papperlapapp/tfd500#1]
Logger Version: 1.0.005

Config:
Status:       NOT recording
Start:        2019-07-19 17:28:08
Interval:     10
Mode:         temperature plus humidity
.# of records: 77

./tfd500_cli.py dump -f
Data will be written to file 'tfd500-20190719.csv'
[                                                            ] 0.0%Traceback (most recent call last):
  File "./tfd500_cli.py", line 364, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./tfd500_cli.py", line 359, in main
    result = args.func(logger, args) or 0
  File "./tfd500_cli.py", line 214, in cmd_dump
    hum if config["humidity"] else None)
  File "./tfd500_cli.py", line 160, in _format_record
    dew, humidity = dewpoint(temperature, humidity)
  File "./tfd500_cli.py", line 132, in dewpoint
    z3 = 0.434292289 * math.log(z2)
ValueError: math domain error

Any idea? Thank you!

**Comment by papperlapapp** [comment]
This means you're living within some desert ;-).
Joking aside, the error comes from `math.log(z2)` and means, `z2` is either less than zero (which it can't be) or exactly zero. Exactly zero is only possible if the humidity is exactly zero. Can you add a`print(temperature, humidity)` when entering the `dewpoint()` function? So we can check the formula used. Maybe we need to catch a special case here.

**Comment by joelands** [comment]
Thank you for the quick response!

Seems to be that I have an other problem ... the USB of the device is not responding (throwing errors). Under Linux and windows as well.
I have to check this first. Maybe the cable or it is killed somehow (I did use ESR protection!)

I will come back then. Have a nice weekend

**Comment by joelands** [comment]
Issue can be closed ... was a problem with my (usb-) hardware. Works now!

**Comment by papperlapapp** [comment]
Thanks for the feedback. I'm still unsure whether or not to catch the still possible edge case.
